spring:
  application:
    name: user-provider
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:import.sql
  config:
    import: optional:configserver:http://localhost:8888